"""Marketplace manifests for AEON's enterprise connector adapters.

The connector engine owns vendor credentials and live transport. These small,
serializable definitions keep the marketplace catalog modular while allowing
each connector to share the normal workspace-scoped install/config/run
lifecycle. The built-in marketplace runner provides safe deterministic health
and sync-preparation actions until a vendor-specific adapter is configured.
"""

from __future__ import annotations

CONNECTOR_PLUGIN_DEFINITIONS = (
    {
        "id": "sage-connector",
        "name": "Sage Connector",
        "version": "1.0.0",
        "description": "Connect Sage accounting data to AEON Finance and the universal Invoice model.",
        "author": "AEON Labs",
        "category": "integration",
        "icon": "🧮",
        "permissions": ("read", "execute", "network"),
        "entry_points": {
            "health": "Check Sage readiness.",
            "sync": "Prepare a Sage synchronization run.",
            "status": "Summarize Sage connector state.",
        },
        "config_schema": {
            "connector_id": {"type": "string", "default": "sage", "description": "Connector engine id."},
            "sync_entities": {"type": "string", "default": "invoice,transaction,payment", "description": "Comma-separated AEON entities."},
        },
        "verified": False,
        "tags": ("sage", "accounting", "erp", "connector"),
    },
    {
        "id": "microsoft365-connector",
        "name": "Microsoft 365 Connector",
        "version": "1.0.0",
        "description": "Connect Microsoft Graph services to AEON Documents, People, Meetings, and Messages.",
        "author": "AEON Labs",
        "category": "integration",
        "icon": "🟦",
        "permissions": ("read", "execute", "network"),
        "entry_points": {
            "health": "Check Microsoft Graph readiness.",
            "sync": "Prepare a Microsoft 365 synchronization run.",
            "status": "Summarize Microsoft 365 connector state.",
        },
        "config_schema": {
            "connector_id": {"type": "string", "default": "microsoft365", "description": "Connector engine id."},
            "sync_entities": {"type": "string", "default": "person,document,email,meeting,message", "description": "Comma-separated AEON entities."},
        },
        "verified": False,
        "tags": ("microsoft365", "graph", "productivity", "connector"),
    },
    {
        "id": "indigo-shireburn-connector",
        "name": "Indigo by Shireburn Connector",
        "version": "1.0.0",
        "description": "Connect Indigo project controls to AEON Projects, Tasks, Budgets, Costs, and Risks.",
        "author": "AEON Labs",
        "category": "integration",
        "icon": "🟧",
        "permissions": ("read", "execute", "network"),
        "entry_points": {
            "health": "Check Indigo by Shireburn readiness.",
            "sync": "Prepare an Indigo synchronization run.",
            "status": "Summarize Indigo connector state.",
        },
        "config_schema": {
            "connector_id": {"type": "string", "default": "indigo", "description": "Connector engine id."},
            "sync_entities": {"type": "string", "default": "project,task,milestone,budget,cost,risk", "description": "Comma-separated AEON entities."},
        },
        "verified": False,
        "tags": ("indigo", "shireburn", "projects", "construction", "connector"),
    },
    {
        "id": "open-time-clock-connector",
        "name": "Open Time Clock Connector",
        "version": "1.0.0",
        "description": "Connect attendance and time records to AEON Workforce and the universal Time Entry model.",
        "author": "AEON Labs",
        "category": "integration",
        "icon": "⏱️",
        "permissions": ("read", "execute", "network"),
        "entry_points": {
            "health": "Check Open Time Clock readiness.",
            "sync": "Prepare an attendance synchronization run.",
            "status": "Summarize time-clock connector state.",
        },
        "config_schema": {
            "connector_id": {"type": "string", "default": "open-time-clock", "description": "Connector engine id."},
            "sync_entities": {"type": "string", "default": "employee,time-entry", "description": "Comma-separated AEON entities."},
        },
        "verified": False,
        "tags": ("open-time-clock", "workforce", "attendance", "connector"),
    },
    {
        "id": "oisoft-connector",
        "name": "OiSoft Connector",
        "version": "1.0.0",
        "description": "Connect OiSoft workforce operations to AEON Workforce, Employees, and Time Entries.",
        "author": "AEON Labs",
        "category": "integration",
        "icon": "🟪",
        "permissions": ("read", "execute", "network"),
        "entry_points": {
            "health": "Check OiSoft readiness.",
            "sync": "Prepare an OiSoft synchronization run.",
            "status": "Summarize OiSoft connector state.",
        },
        "config_schema": {
            "connector_id": {"type": "string", "default": "oisoft", "description": "Connector engine id."},
            "sync_entities": {"type": "string", "default": "employee,time-entry", "description": "Comma-separated AEON entities."},
        },
        "verified": False,
        "tags": ("oisoft", "workforce", "operations", "connector"),
    },
    {
        "id": "xero-connector",
        "name": "Xero Connector",
        "version": "1.0.0",
        "description": "Connect Xero accounting data to AEON Finance, Invoices, Payments, and Transactions.",
        "author": "AEON Labs",
        "category": "integration",
        "icon": "🧾",
        "permissions": ("read", "execute", "network"),
        "entry_points": {
            "health": "Check Xero readiness.",
            "sync": "Prepare a Xero synchronization run.",
            "status": "Summarize Xero connector state.",
        },
        "config_schema": {
            "connector_id": {"type": "string", "default": "xero", "description": "Connector engine id."},
            "sync_entities": {"type": "string", "default": "invoice,payment,transaction,financial-account", "description": "Comma-separated AEON entities."},
        },
        "verified": False,
        "tags": ("xero", "accounting", "erp", "connector"),
    },
    {
        "id": "quickbooks-connector",
        "name": "QuickBooks Connector",
        "version": "1.0.0",
        "description": "Connect QuickBooks accounting data to AEON Finance, Invoices, and Customers.",
        "author": "AEON Labs",
        "category": "integration",
        "icon": "💹",
        "permissions": ("read", "execute", "network"),
        "entry_points": {
            "health": "Check QuickBooks readiness.",
            "sync": "Prepare a QuickBooks synchronization run.",
            "status": "Summarize QuickBooks connector state.",
        },
        "config_schema": {
            "connector_id": {"type": "string", "default": "quickbooks", "description": "Connector engine id."},
            "sync_entities": {"type": "string", "default": "invoice,payment,transaction,customer", "description": "Comma-separated AEON entities."},
        },
        "verified": False,
        "tags": ("quickbooks", "accounting", "erp", "connector"),
    },
    {
        "id": "sap-connector",
        "name": "SAP Connector",
        "version": "1.0.0",
        "description": "Connect SAP ERP data to AEON Finance, Orders, Products, and Financial Accounts.",
        "author": "AEON Labs",
        "category": "integration",
        "icon": "🟨",
        "permissions": ("read", "execute", "network"),
        "entry_points": {
            "health": "Check SAP readiness.",
            "sync": "Prepare a SAP synchronization run.",
            "status": "Summarize SAP connector state.",
        },
        "config_schema": {
            "connector_id": {"type": "string", "default": "sap", "description": "Connector engine id."},
            "sync_entities": {"type": "string", "default": "invoice,order,product,financial-account", "description": "Comma-separated AEON entities."},
        },
        "verified": False,
        "tags": ("sap", "erp", "enterprise", "connector"),
    },
    {
        "id": "salesforce-connector",
        "name": "Salesforce Connector",
        "version": "1.0.0",
        "description": "Connect Salesforce CRM data to AEON Customers, People, and Organizations.",
        "author": "AEON Labs",
        "category": "integration",
        "icon": "☁️",
        "permissions": ("read", "execute", "network"),
        "entry_points": {
            "health": "Check Salesforce readiness.",
            "sync": "Prepare a Salesforce synchronization run.",
            "status": "Summarize Salesforce connector state.",
        },
        "config_schema": {
            "connector_id": {"type": "string", "default": "salesforce", "description": "Connector engine id."},
            "sync_entities": {"type": "string", "default": "customer,person,organization,order", "description": "Comma-separated AEON entities."},
        },
        "verified": False,
        "tags": ("salesforce", "crm", "sales", "connector"),
    },
    {
        "id": "hubspot-connector",
        "name": "HubSpot Connector",
        "version": "1.0.0",
        "description": "Connect HubSpot CRM and marketing data to AEON Customers, People, and Organizations.",
        "author": "AEON Labs",
        "category": "integration",
        "icon": "🟠",
        "permissions": ("read", "execute", "network"),
        "entry_points": {
            "health": "Check HubSpot readiness.",
            "sync": "Prepare a HubSpot synchronization run.",
            "status": "Summarize HubSpot connector state.",
        },
        "config_schema": {
            "connector_id": {"type": "string", "default": "hubspot", "description": "Connector engine id."},
            "sync_entities": {"type": "string", "default": "customer,person,organization,order", "description": "Comma-separated AEON entities."},
        },
        "verified": False,
        "tags": ("hubspot", "crm", "marketing", "connector"),
    },
    {
        "id": "stripe-connector",
        "name": "Stripe Connector",
        "version": "1.0.0",
        "description": "Connect Stripe payment data to AEON Payments, Transactions, Orders, and Customers.",
        "author": "AEON Labs",
        "category": "integration",
        "icon": "💳",
        "permissions": ("read", "execute", "network"),
        "entry_points": {
            "health": "Check Stripe readiness.",
            "sync": "Prepare a Stripe synchronization run.",
            "status": "Summarize Stripe connector state.",
        },
        "config_schema": {
            "connector_id": {"type": "string", "default": "stripe", "description": "Connector engine id."},
            "sync_entities": {"type": "string", "default": "payment,transaction,order,customer", "description": "Comma-separated AEON entities."},
        },
        "verified": False,
        "tags": ("stripe", "payments", "billing", "connector"),
    },
    {
        "id": "shopify-connector",
        "name": "Shopify Connector",
        "version": "1.0.0",
        "description": "Connect Shopify storefront data to AEON Products, Orders, Inventory, and Payments.",
        "author": "AEON Labs",
        "category": "integration",
        "icon": "🛍️",
        "permissions": ("read", "execute", "network"),
        "entry_points": {
            "health": "Check Shopify readiness.",
            "sync": "Prepare a Shopify synchronization run.",
            "status": "Summarize Shopify connector state.",
        },
        "config_schema": {
            "connector_id": {"type": "string", "default": "shopify", "description": "Connector engine id."},
            "sync_entities": {"type": "string", "default": "product,order,inventory,payment", "description": "Comma-separated AEON entities."},
        },
        "verified": False,
        "tags": ("shopify", "ecommerce", "retail", "connector"),
    },
    {
        "id": "pos-connector",
        "name": "POS Connector",
        "version": "1.0.0",
        "description": "Connect point-of-sale data to AEON Products, Orders, Sales, Payments, and Inventory.",
        "author": "AEON Labs",
        "category": "integration",
        "icon": "🛒",
        "permissions": ("read", "execute", "network"),
        "entry_points": {
            "health": "Check POS readiness.",
            "sync": "Prepare a POS synchronization run.",
            "status": "Summarize POS connector state.",
        },
        "config_schema": {
            "connector_id": {"type": "string", "default": "pos", "description": "Connector engine id."},
            "sync_entities": {"type": "string", "default": "product,order,payment,inventory", "description": "Comma-separated AEON entities."},
        },
        "verified": False,
        "tags": ("pos", "retail", "restaurant", "connector"),
    },
    {
        "id": "google-workspace-connector",
        "name": "Google Workspace Connector",
        "version": "1.0.0",
        "description": "Connect Google Workspace services to AEON People, Email, Meetings, Documents, and Messages.",
        "author": "AEON Labs",
        "category": "integration",
        "icon": "🟩",
        "permissions": ("read", "execute", "network"),
        "entry_points": {
            "health": "Check Google Workspace readiness.",
            "sync": "Prepare a Google Workspace synchronization run.",
            "status": "Summarize Google Workspace connector state.",
        },
        "config_schema": {
            "connector_id": {"type": "string", "default": "google-workspace", "description": "Connector engine id."},
            "sync_entities": {"type": "string", "default": "person,email,meeting,document,message", "description": "Comma-separated AEON entities."},
        },
        "verified": False,
        "tags": ("google-workspace", "productivity", "collaboration", "connector"),
    },
    {
        "id": "slack-connector",
        "name": "Slack Connector",
        "version": "1.0.0",
        "description": "Connect Slack conversations to AEON Messages, People, and Organizations.",
        "author": "AEON Labs",
        "category": "integration",
        "icon": "💬",
        "permissions": ("read", "execute", "network"),
        "entry_points": {
            "health": "Check Slack readiness.",
            "sync": "Prepare a Slack synchronization run.",
            "status": "Summarize Slack connector state.",
        },
        "config_schema": {
            "connector_id": {"type": "string", "default": "slack", "description": "Connector engine id."},
            "sync_entities": {"type": "string", "default": "message,person,organization", "description": "Comma-separated AEON entities."},
        },
        "verified": False,
        "tags": ("slack", "communication", "messaging", "connector"),
    },
    {
        "id": "jira-connector",
        "name": "Jira Connector",
        "version": "1.0.0",
        "description": "Connect Jira project data to AEON Projects, Tasks, Risks, and Events.",
        "author": "AEON Labs",
        "category": "integration",
        "icon": "🎯",
        "permissions": ("read", "execute", "network"),
        "entry_points": {
            "health": "Check Jira readiness.",
            "sync": "Prepare a Jira synchronization run.",
            "status": "Summarize Jira connector state.",
        },
        "config_schema": {
            "connector_id": {"type": "string", "default": "jira", "description": "Connector engine id."},
            "sync_entities": {"type": "string", "default": "project,task,risk,event", "description": "Comma-separated AEON entities."},
        },
        "verified": False,
        "tags": ("jira", "project-management", "devops", "connector"),
    },
    {
        "id": "zendesk-connector",
        "name": "Zendesk Connector",
        "version": "1.0.0",
        "description": "Connect Zendesk support data to AEON Customers, People, Messages, and Events.",
        "author": "AEON Labs",
        "category": "integration",
        "icon": "🎧",
        "permissions": ("read", "execute", "network"),
        "entry_points": {
            "health": "Check Zendesk readiness.",
            "sync": "Prepare a Zendesk synchronization run.",
            "status": "Summarize Zendesk connector state.",
        },
        "config_schema": {
            "connector_id": {"type": "string", "default": "zendesk", "description": "Connector engine id."},
            "sync_entities": {"type": "string", "default": "customer,person,message,event", "description": "Comma-separated AEON entities."},
        },
        "verified": False,
        "tags": ("zendesk", "support", "helpdesk", "connector"),
    },
    {
        "id": "workday-connector",
        "name": "Workday Connector",
        "version": "1.0.0",
        "description": "Connect Workday HCM data to AEON Employees, People, and Organizations.",
        "author": "AEON Labs",
        "category": "integration",
        "icon": "👥",
        "permissions": ("read", "execute", "network"),
        "entry_points": {
            "health": "Check Workday readiness.",
            "sync": "Prepare a Workday synchronization run.",
            "status": "Summarize Workday connector state.",
        },
        "config_schema": {
            "connector_id": {"type": "string", "default": "workday", "description": "Connector engine id."},
            "sync_entities": {"type": "string", "default": "employee,person,organization,event", "description": "Comma-separated AEON entities."},
        },
        "verified": False,
        "tags": ("workday", "hcm", "hr", "connector"),
    },
    {
        "id": "bamboohr-connector",
        "name": "BambooHR Connector",
        "version": "1.0.0",
        "description": "Connect BambooHR people data to AEON Employees, People, and Organizations.",
        "author": "AEON Labs",
        "category": "integration",
        "icon": "🌿",
        "permissions": ("read", "execute", "network"),
        "entry_points": {
            "health": "Check BambooHR readiness.",
            "sync": "Prepare a BambooHR synchronization run.",
            "status": "Summarize BambooHR connector state.",
        },
        "config_schema": {
            "connector_id": {"type": "string", "default": "bamboohr", "description": "Connector engine id."},
            "sync_entities": {"type": "string", "default": "employee,person,organization", "description": "Comma-separated AEON entities."},
        },
        "verified": False,
        "tags": ("bamboohr", "hr", "people", "connector"),
    },
    {
        "id": "docusign-connector",
        "name": "DocuSign Connector",
        "version": "1.0.0",
        "description": "Connect DocuSign agreements to AEON Documents, Events, and Alerts.",
        "author": "AEON Labs",
        "category": "integration",
        "icon": "✍️",
        "permissions": ("read", "execute", "network"),
        "entry_points": {
            "health": "Check DocuSign readiness.",
            "sync": "Prepare a DocuSign synchronization run.",
            "status": "Summarize DocuSign connector state.",
        },
        "config_schema": {
            "connector_id": {"type": "string", "default": "docusign", "description": "Connector engine id."},
            "sync_entities": {"type": "string", "default": "document,event,alert", "description": "Comma-separated AEON entities."},
        },
        "verified": False,
        "tags": ("docusign", "esignature", "documents", "connector"),
    },
    {
        "id": "twilio-connector",
        "name": "Twilio Connector",
        "version": "1.0.0",
        "description": "Connect Twilio communications to AEON Messages, Events, and Alerts.",
        "author": "AEON Labs",
        "category": "integration",
        "icon": "📱",
        "permissions": ("read", "execute", "network"),
        "entry_points": {
            "health": "Check Twilio readiness.",
            "sync": "Prepare a Twilio synchronization run.",
            "status": "Summarize Twilio connector state.",
        },
        "config_schema": {
            "connector_id": {"type": "string", "default": "twilio", "description": "Connector engine id."},
            "sync_entities": {"type": "string", "default": "message,event,alert", "description": "Comma-separated AEON entities."},
        },
        "verified": False,
        "tags": ("twilio", "sms", "communication", "connector"),
    },
)
