"""AEON OS structured error codes.

These constants are used by ``_error_response`` in ``aeon_server.py`` and
can be imported on the frontend for consistent client-side error handling.
"""

from __future__ import annotations

# ── Authentication / Authorization ───────────────────────────────────────────
MISSING_CREDENTIALS = "MISSING_CREDENTIALS"
INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
WEAK_PASSWORD = "WEAK_PASSWORD"
EMAIL_TAKEN = "EMAIL_TAKEN"
REGISTRATION_FAILED = "REGISTRATION_FAILED"
USER_NOT_FOUND = "USER_NOT_FOUND"
TOKEN_EXPIRED = "TOKEN_EXPIRED"
TOKEN_INVALID = "TOKEN_INVALID"
ACCOUNT_DISABLED = "ACCOUNT_DISABLED"
UNAUTHORIZED = "UNAUTHORIZED"
FORBIDDEN = "FORBIDDEN"

# ── Workspace / Tenant ───────────────────────────────────────────────────────
WORKSPACE_NOT_SELECTED = "WORKSPACE_NOT_SELECTED"
WORKSPACE_NOT_FOUND = "WORKSPACE_NOT_FOUND"
WORKSPACE_ACCESS_DENIED = "WORKSPACE_ACCESS_DENIED"
WORKSPACE_ADMIN_REQUIRED = "WORKSPACE_ADMIN_REQUIRED"
WORKSPACE_OPERATOR_REQUIRED = "WORKSPACE_OPERATOR_REQUIRED"
MEMBERSHIP_NOT_FOUND = "MEMBERSHIP_NOT_FOUND"
MEMBERSHIP_EXISTS = "MEMBERSHIP_EXISTS"
ROLE_INVALID = "ROLE_INVALID"

# ── Input validation ─────────────────────────────────────────────────────────
VALIDATION_ERROR = "VALIDATION_ERROR"
MISSING_FIELD = "MISSING_FIELD"
INVALID_PAYLOAD = "INVALID_PAYLOAD"
INVALID_CRON = "INVALID_CRON"
INVALID_ACTION_TYPE = "INVALID_ACTION_TYPE"
INVALID_EFFECT = "INVALID_EFFECT"
INVALID_PLAN = "INVALID_PLAN"
INVALID_PERIOD = "INVALID_PERIOD"
AMOUNT_MUST_BE_POSITIVE = "AMOUNT_MUST_BE_POSITIVE"

# ── Resources ────────────────────────────────────────────────────────────────
NOT_FOUND = "NOT_FOUND"
ALREADY_EXISTS = "ALREADY_EXISTS"

# ── Stripe / Billing ─────────────────────────────────────────────────────────
STRIPE_NOT_CONFIGURED = "STRIPE_NOT_CONFIGURED"
STRIPE_ERROR = "STRIPE_ERROR"
CHECKOUT_FAILED = "CHECKOUT_FAILED"
SUBSCRIPTION_NOT_FOUND = "SUBSCRIPTION_NOT_FOUND"

# ── LLM / AI ─────────────────────────────────────────────────────────────────
LLM_PROVIDER_NOT_CONFIGURED = "LLM_PROVIDER_NOT_CONFIGURED"
LLM_REQUEST_FAILED = "LLM_REQUEST_FAILED"
PROVIDER_REQUIRED = "PROVIDER_REQUIRED"

# ── Integrations / Plugins ───────────────────────────────────────────────────
INTEGRATION_NOT_FOUND = "INTEGRATION_NOT_FOUND"
INTEGRATION_ID_REQUIRED = "INTEGRATION_ID_REQUIRED"
PLUGIN_NOT_FOUND = "PLUGIN_NOT_FOUND"

# ── Automations ──────────────────────────────────────────────────────────────
RULE_NOT_FOUND = "RULE_NOT_FOUND"
EXECUTION_NOT_FOUND = "EXECUTION_NOT_FOUND"
APPROVAL_NOT_FOUND = "APPROVAL_NOT_FOUND"
SUPERVISOR_REQUIRED = "SUPERVISOR_REQUIRED"

# ── Knowledge base ───────────────────────────────────────────────────────────
KB_NOT_FOUND = "KB_NOT_FOUND"
KB_CHUNK_FAILED = "KB_CHUNK_FAILED"
KB_SEARCH_FAILED = "KB_SEARCH_FAILED"

# ── API keys ─────────────────────────────────────────────────────────────────
API_KEY_MISSING = "API_KEY_MISSING"
API_KEY_INVALID = "API_KEY_INVALID"
API_KEY_RATE_LIMITED = "API_KEY_RATE_LIMITED"
KEY_NOT_FOUND = "KEY_NOT_FOUND"
KEY_UPDATE_FAILED = "KEY_UPDATE_FAILED"
KEY_ROTATION_FAILED = "KEY_ROTATION_FAILED"

# ── Sector packs / Governance ────────────────────────────────────────────────
POLICY_NOT_FOUND = "POLICY_NOT_FOUND"
BUDGET_NOT_FOUND = "BUDGET_NOT_FOUND"
SNAPSHOT_NOT_FOUND = "SNAPSHOT_NOT_FOUND"

# ── SCIM ─────────────────────────────────────────────────────────────────────
SCIM_UNAUTHORIZED = "SCIM_UNAUTHORIZED"
SCIM_TOKEN_INVALID = "SCIM_TOKEN_INVALID"

# ── Infra / Subsystem ────────────────────────────────────────────────────────
SUPABASE_NOT_CONFIGURED = "SUPABASE_NOT_CONFIGURED"
INTERNAL_ERROR = "INTERNAL_ERROR"
SUBSYSTEM_UNAVAILABLE = "SUBSYSTEM_UNAVAILABLE"
RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED"
