"""Universal, cross-industry marketplace plugins for AEON OS.

These manifests describe capabilities that are useful across sectors and do not
belong to a specific vendor or industry pack. They are intentionally declarative
so the marketplace lifecycle remains the single installation surface.
"""

from __future__ import annotations

UNIVERSAL_PLUGIN_DEFINITIONS = (
    {
        "id": "universal-search",
        "name": "Universal Search",
        "version": "1.0.0",
        "description": "Search canonical AEON entities across enabled modules and connected systems with tenant-scoped results.",
        "author": "AEON Labs",
        "category": "data",
        "icon": "🔎",
        "permissions": ("read", "execute"),
        "entry_points": {
            "summary": "Search tenant-scoped canonical records and documents.",
            "report": "Return searchable fields and source facets.",
            "profile": "Explain which modules and connectors contributed results.",
        },
        "config_schema": {
            "scope": {"type": "string", "default": "tenant", "description": "Search scope; tenant is always enforced."},
            "max_results": {"type": "number", "default": 25, "description": "Maximum result count."},
        },
        "verified": True,
        "tags": ("search", "universal-model", "tenant", "cross-sector"),
    },
    {
        "id": "data-lineage",
        "name": "Data Lineage",
        "version": "1.0.0",
        "description": "Track source, normalization, transformations, and provenance for every universal AEON record.",
        "author": "AEON Labs",
        "category": "data",
        "icon": "🧬",
        "permissions": ("read", "execute"),
        "entry_points": {
            "trace": "Trace a canonical record back to its source system.",
            "status": "List source systems and transformations for an entity.",
            "report": "Prepare a provenance report for review or audit.",
        },
        "config_schema": {
            "retention_days": {"type": "number", "default": 365, "description": "Lineage retention window."},
            "include_raw": {"type": "boolean", "default": False, "description": "Include raw source references when permitted."},
        },
        "verified": True,
        "tags": ("lineage", "provenance", "audit", "universal-model"),
    },
    {
        "id": "tenant-onboarding",
        "name": "Tenant Onboarding",
        "version": "1.0.0",
        "description": "Guide a new company from industry selection through modules, connectors, permissions, and readiness checks.",
        "author": "AEON Labs",
        "category": "automation",
        "icon": "🚀",
        "permissions": ("read", "execute", "notify"),
        "entry_points": {
            "profile": "Return the onboarding checklist for a tenant.",
            "check": "Validate a proposed tenant configuration before saving.",
            "summary": "Summarize onboarding readiness and remaining steps.",
        },
        "config_schema": {
            "industry": {"type": "string", "default": "core", "description": "Industry pack to configure."},
            "require_connector_health": {"type": "boolean", "default": True, "description": "Require connector readiness before completion."},
        },
        "verified": True,
        "tags": ("onboarding", "tenant", "configuration", "implementation"),
    },
    {
        "id": "universal-inbox",
        "name": "Universal Inbox",
        "version": "1.0.0",
        "description": "Aggregate Email, Meeting, and Message canonical records from every connected system into one tenant inbox.",
        "author": "AEON Labs",
        "category": "communication",
        "icon": "📥",
        "permissions": ("read", "execute", "notify"),
        "entry_points": {
            "summary": "Summarize items aggregated from all connected sources.",
            "status": "Report per-source sync and read state.",
            "review": "Review actionable items across the inbox.",
        },
        "config_schema": {
            "max_sources": {"type": "number", "default": 50, "description": "Maximum connected sources to aggregate."},
            "dedupe": {"type": "boolean", "default": True, "description": "Merge duplicate canonical records."},
            "mark_read_sync": {"type": "boolean", "default": True, "description": "Propagate read state back to source systems."},
        },
        "verified": True,
        "tags": ("inbox", "communication", "universal-model", "cross-sector"),
    },
    {
        "id": "universal-notifications",
        "name": "Universal Notifications",
        "version": "1.0.0",
        "description": "Orchestrate cross-channel notifications (in-app, email, SMS, webhook) with per-tenant routing and digest rules.",
        "author": "AEON Labs",
        "category": "communication",
        "icon": "🔔",
        "permissions": ("read", "execute", "notify"),
        "entry_points": {
            "status": "Report delivery status per channel.",
            "schedule": "Schedule a notification or digest delivery.",
            "suggest": "Suggest the best channels for a notification.",
        },
        "config_schema": {
            "channels": {"type": "string", "default": "in-app,email", "description": "Comma-separated enabled channels."},
            "digest_hour": {"type": "number", "default": 8, "description": "Hour (0-23) for daily digests."},
            "require_consent": {"type": "boolean", "default": True, "description": "Respect per-user channel consent."},
        },
        "verified": True,
        "tags": ("notifications", "communication", "alerts", "cross-sector"),
    },
    {
        "id": "universal-documents",
        "name": "Universal Documents",
        "version": "1.0.0",
        "description": "Canonical document store with versioning, OCR indexing, and retention for any industry's files.",
        "author": "AEON Labs",
        "category": "productivity",
        "icon": "📄",
        "permissions": ("read", "write", "execute"),
        "entry_points": {
            "index": "Index a document into the canonical store.",
            "retrieve": "Retrieve a tenant document with version context.",
            "sync": "Sync documents with connected source systems.",
        },
        "config_schema": {
            "retention_days": {"type": "number", "default": 730, "description": "Document retention window."},
            "versioning": {"type": "boolean", "default": True, "description": "Keep full version history."},
            "ocr": {"type": "boolean", "default": False, "description": "Extract text from scanned documents."},
        },
        "verified": True,
        "tags": ("documents", "dms", "versioning", "universal-model"),
    },
    {
        "id": "contracts-vault",
        "name": "Contracts Vault",
        "version": "1.0.0",
        "description": "Canonical contracts and agreements store with expiry tracking, renewals, and approval handoff.",
        "author": "AEON Labs",
        "category": "productivity",
        "icon": "📜",
        "permissions": ("read", "write", "execute", "notify"),
        "entry_points": {
            "report": "Prepare a contract portfolio report.",
            "review": "Review contracts by status and expiry.",
            "schedule": "Schedule renewal and expiry reminders.",
        },
        "config_schema": {
            "expiry_lead_days": {"type": "number", "default": 60, "description": "Days before expiry to flag renewal."},
            "require_approval": {"type": "boolean", "default": True, "description": "Require approval for contract changes."},
            "categories": {"type": "string", "default": "commercial,procurement,hr", "description": "Comma-separated default categories."},
        },
        "verified": True,
        "tags": ("contracts", "procurement", "legal", "compliance"),
    },
    {
        "id": "insight-engine",
        "name": "Insight Engine",
        "version": "1.0.0",
        "description": "Cross-module KPI builder on the canonical data model with dashboards and scheduled reports.",
        "author": "AEON Labs",
        "category": "analytics",
        "icon": "📊",
        "permissions": ("read", "execute", "notify"),
        "entry_points": {
            "analyze": "Analyze a canonical metric over a period.",
            "build": "Build a KPI definition on canonical metrics.",
            "report": "Render a dashboard or scheduled report.",
        },
        "config_schema": {
            "schedule": {"type": "string", "default": "daily", "description": "Report cadence: daily, weekly, monthly."},
            "history_days": {"type": "number", "default": 90, "description": "Default analysis window."},
            "export_format": {"type": "string", "default": "csv,json,pdf", "description": "Allowed export formats."},
        },
        "verified": True,
        "tags": ("analytics", "kpi", "dashboards", "reports"),
    },
    {
        "id": "forecasting-engine",
        "name": "Forecasting Engine",
        "version": "1.0.0",
        "description": "Time-series forecasting on any canonical metric with confidence intervals and validation.",
        "author": "AEON Labs",
        "category": "ai",
        "icon": "🔮",
        "permissions": ("read", "execute"),
        "entry_points": {
            "forecast": "Forecast a canonical metric series.",
            "assess": "Assess forecast quality against held-out history.",
            "report": "Summarize a forecast with confidence intervals.",
        },
        "config_schema": {
            "horizon_days": {"type": "number", "default": 90, "description": "Forecast horizon."},
            "confidence_level": {"type": "number", "default": 0.9, "description": "Confidence interval level."},
            "min_history_days": {"type": "number", "default": 30, "description": "Minimum history to forecast."},
        },
        "verified": True,
        "tags": ("forecasting", "ai", "predictive", "analytics"),
    },
    {
        "id": "risk-register",
        "name": "Risk Register",
        "version": "1.0.0",
        "description": "Tenant-wide risk register with likelihood-impact scoring, owners, and mitigation tracking.",
        "author": "AEON Labs",
        "category": "analytics",
        "icon": "⚠️",
        "permissions": ("read", "write", "execute", "notify"),
        "entry_points": {
            "assess": "Score and re-score a risk with current context.",
            "report": "Summarize open risks and mitigations.",
            "escalate": "Escalate high-severity risks to owners.",
        },
        "config_schema": {
            "scoring_model": {"type": "string", "default": "likelihood-impact", "description": "Scoring model in use."},
            "review_interval_days": {"type": "number", "default": 30, "description": "Required review cadence."},
            "require_owner": {"type": "boolean", "default": True, "description": "Every risk needs an owner."},
        },
        "verified": True,
        "tags": ("risk", "governance", "compliance", "mitigation"),
    },
    {
        "id": "audit-engine",
        "name": "Audit Engine",
        "version": "1.0.0",
        "description": "Immutable tenant-scoped audit log with encrypted export and alerts on sensitive actions.",
        "author": "AEON Labs",
        "category": "security",
        "icon": "🛡️",
        "permissions": ("read", "execute", "notify", "admin"),
        "entry_points": {
            "trace": "Trace tenant-scoped audit records for an entity.",
            "export": "Export an encrypted audit report.",
            "rules": "List alert rules for sensitive actions.",
        },
        "config_schema": {
            "retention_days": {"type": "number", "default": 3650, "description": "Audit retention window."},
            "alert_on_sensitive": {"type": "boolean", "default": True, "description": "Alert on sensitive actions."},
            "export_encrypted": {"type": "boolean", "default": True, "description": "Encrypt audit exports."},
        },
        "verified": True,
        "tags": ("audit", "security", "compliance", "traceability"),
    },
    {
        "id": "workflow-studio",
        "name": "Workflow Studio",
        "version": "1.0.0",
        "description": "Low-code workflow builder that wires module events to actions with approvals and webhooks.",
        "author": "AEON Labs",
        "category": "automation",
        "icon": "🧩",
        "permissions": ("read", "write", "execute", "notify"),
        "entry_points": {
            "trigger": "Trigger a workflow from module events.",
            "status": "Report workflow run status and approvals.",
            "approve": "Approve or reject a pending workflow step.",
        },
        "config_schema": {
            "max_steps": {"type": "number", "default": 20, "description": "Maximum steps per workflow."},
            "allow_webhooks": {"type": "boolean", "default": True, "description": "Allow webhook triggers and actions."},
            "approval_default": {"type": "boolean", "default": True, "description": "Require approval for new workflows."},
        },
        "verified": True,
        "tags": ("workflow", "automation", "bpa", "approvals"),
    },
)
