[phases.setup]
nixPkgs = ["nodejs", "nodePackages.pnpm"]
nixOverlays = []

[phases.install]
cmds = [
  "cd web && npm install 2>&1"
]

[phases.build]
cmds = ["cd web && npm run build 2>&1"]

[start]
cmd = "cd web && npm run start"
