#!/usr/bin/env sh
# AEON OS — one-command bootstrap for a fresh Oracle Cloud VM
# ============================================================
# Run ON the VM (Ubuntu 22.04+/Debian 12, ARM Ampere A1 or x86):
#   sh scripts/deploy-oracle.sh https://github.com/beatznlg/aeon.git
#
# Installs Docker, generates secrets, opens host firewall ports 80/443,
# and starts the full stack (Postgres + Redis + Flask + workers + Next.js + Caddy).

set -eu

REPO_URL="${1:-https://github.com/beatznlg/aeon.git}"
APP_DIR="${AEON_APP_DIR:-/opt/aeon}"
BRANCH="${AEON_BRANCH:-main}"

echo "=== AEON OS — Oracle Cloud bootstrap ==="

if ! command -v docker >/dev/null 2>&1; then
    echo "Installing Docker..."
    curl -fsSL https://get.docker.com | sh
fi
docker compose version >/dev/null 2>&1 || { echo "Docker Compose v2 required"; exit 1; }

for PORT in 80 443; do
    if ! iptables -C INPUT -p tcp --dport "$PORT" -j ACCEPT 2>/dev/null; then
        REJ=$(iptables -L INPUT -n --line-numbers | awk '/REJECT/{print $1; exit}')
        POS=${REJ:-1}
        iptables -I INPUT "$POS" -p tcp --dport "$PORT" -j ACCEPT && echo "opened port $PORT in iptables"
    fi
done
command -v netfilter-persistent >/dev/null && netfilter-persistent save >/dev/null || true
ufw status 2>/dev/null | grep -q active && ufw allow 80,443/tcp >/dev/null || true

if [ -d "$APP_DIR/.git" ]; then
    git -C "$APP_DIR" fetch origin "$BRANCH"
    git -C "$APP_DIR" reset --hard "origin/$BRANCH"
else
    git clone --depth 1 --branch "$BRANCH" "$REPO_URL" "$APP_DIR"
fi
cd "$APP_DIR"

sudo systemctl disable --now aeon-backend aeon-web caddy 2>/dev/null || true
sudo pkill -f 'gunicorn.*aeon_server' 2>/dev/null || true
pgrep -x caddy >/dev/null && sudo pkill -x caddy || true

# Secrets are generated once and preserved across updates. Each security
# boundary receives an independent key; never reuse JWT/auth material for data encryption.
if [ ! -f .env ]; then
    echo "Generating production secrets..."
    gen() { head -c 48 /dev/urandom | base64 | tr -d '/+=' | head -c "$1"; }
    POSTGRES_PASSWORD="$(gen 40)"
    AUTH_SECRET="$(gen 64)"
    JWT_SECRET="$(gen 64)"
    API_TOKEN="$(gen 64)"
    KMS_KEY="$(gen 64)"
    cat > .env <<EOF
# AEON OS production secrets (generated $(date -u +%Y-%m-%dT%H:%M:%SZ))
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
AUTH_SECRET=$AUTH_SECRET
AEON_JWT_SECRET=$JWT_SECRET
AEON_API_TOKEN=$API_TOKEN
AEON_MASTER_KMS_KEY=$KMS_KEY

# Point at your DNS name (A record -> this VM's public IP) for HTTPS.
# Until then Caddy serves plain HTTP on :80.
AEON_DOMAIN=
NEXTAUTH_URL=
AEON_CORS_ALLOWED_ORIGINS=
NEXT_PUBLIC_APP_NAME=AEON OS
NEXT_PUBLIC_APP_URL=

# First-boot admin seed. A random password is generated by env-repair when absent.
AEON_ADMIN_EMAIL=admin@aeon.local
AEON_ADMIN_PASSWORD=
AEON_ADMIN_NAME=Platform Admin

# LLM provider: stub | openai | anthropic | google | mistral | openrouter ...
AEON_LLM_PROVIDER=stub
OPENAI_API_KEY=
ANTHROPIC_API_KEY=
GOOGLE_API_KEY=
MISTRAL_API_KEY=
OPENROUTER_API_KEY=
HUGGINGFACE_TOKEN=

# Billing (optional until Stripe is enabled)
STRIPE_API_KEY=
STRIPE_WEBHOOK_SECRET=
STRIPE_PRICE_TEAM=
STRIPE_PRICE_ENTERPRISE=
EOF
    chmod 600 .env
fi

sh "$APP_DIR/scripts/aeon-env-repair.sh"

echo ""
echo "Admin login (save these credentials securely and rotate after first login):"
if [ -f "$APP_DIR/.env" ]; then
    _email=$(sed -n 's/^AEON_ADMIN_EMAIL=//p' "$APP_DIR/.env" | head -1)
    _pass=$(sed -n 's/^AEON_ADMIN_PASSWORD=//p' "$APP_DIR/.env" | head -1)
    echo "  Email:    $_email"
    echo "  Password: $_pass"
fi

echo ""
echo "NOTE: OCI Security List / NSG must allow ingress TCP 80 and 443."
echo "Starting stack..."
docker compose -f docker-compose.oci.yml up -d --build --remove-orphans

if [ "$(id -u)" = 0 ]; then
    sh "$APP_DIR/scripts/install-autoupdate.sh"
else
    echo "Tip: run 'sudo sh scripts/install-autoupdate.sh' to enable the auto-update timer."
fi

echo ""
echo "=== Done. Check status:  docker compose -f docker-compose.oci.yml ps"
echo "Kernel health:           curl http://localhost/health"
echo "Auto-update timer:       systemctl list-timers aeon-autoupdate.timer"
