#!/usr/bin/env sh
# AEON OS — one-command bootstrap for a fresh Oracle Cloud VM
# ============================================================
# Run ON the VM (Ubuntu 22.04+/Debian 12, ARM Ampere A1 or x86):
#   sh scripts/deploy-oracle.sh https://github.com/beatznlg/aeon.git
#
# Installs Docker, generates secrets, opens host firewall ports 80/443,
# and starts the full stack (Postgres + Flask kernel + Next.js web + Caddy).
# Re-run any time to update to the latest main branch.

set -eu

REPO_URL="${1:-https://github.com/beatznlg/aeon.git}"
APP_DIR="${AEON_APP_DIR:-/opt/aeon}"
BRANCH="${AEON_BRANCH:-main}"

echo "=== AEON OS — Oracle Cloud bootstrap ==="

# ── Docker ──────────────────────────────────────────────────────────────────
if ! command -v docker >/dev/null 2>&1; then
    echo "Installing Docker..."
    curl -fsSL https://get.docker.com | sh
fi
docker compose version >/dev/null 2>&1 || { echo "Docker Compose v2 required"; exit 1; }

# ── Host firewall: open 80/443 before the iptables REJECT rule ─────────────
# Ubuntu images ship a default REJECT-after-allow rule; without this the site
# times out from outside even when the OCI Security List is correct.
for PORT in 80 443; do
    if ! iptables -C INPUT -p tcp --dport "$PORT" -j ACCEPT 2>/dev/null; then
        REJ=$(iptables -L INPUT -n --line-numbers | awk '/REJECT/{print $1; exit}')
        POS=${REJ:-1}
        iptables -I INPUT "$POS" -p tcp --dport "$PORT" -j ACCEPT && echo "opened port $PORT in iptables"
    fi
done
command -v netfilter-persistent >/dev/null && netfilter-persistent save >/dev/null || true
ufw status 2>/dev/null | grep -q active && ufw allow 80,443/tcp >/dev/null || true

# ── Code ────────────────────────────────────────────────────────────────────
if [ -d "$APP_DIR/.git" ]; then
    git -C "$APP_DIR" fetch origin "$BRANCH"
    git -C "$APP_DIR" reset --hard "origin/$BRANCH"
else
    git clone --depth 1 --branch "$BRANCH" "$REPO_URL" "$APP_DIR"
fi
cd "$APP_DIR"

# Stop any legacy native stack that would collide with container ports.
sudo systemctl disable --now aeon-backend aeon-web caddy 2>/dev/null || true
sudo pkill -f 'gunicorn.*aeon_server' 2>/dev/null || true
pgrep -x caddy >/dev/null && sudo pkill -x caddy || true

# ── Secrets (.env created once, preserved across updates) ──────────────────
if [ ! -f .env ]; then
    echo "Generating production secrets..."
    POSTGRES_PASSWORD="$(head -c 32 /dev/urandom | base64 | tr -d '/+=' | head -c 32)"
    AUTH_SECRET="$(head -c 32 /dev/urandom | base64 | tr -d '/+=' | head -c 48)"
    JWT_SECRET="$(head -c 32 /dev/urandom | base64 | tr -d '/+=' | head -c 48)"
    API_TOKEN="$(head -c 32 /dev/urandom | base64 | tr -d '/+=' | head -c 48)"
    cat > .env <<EOF
# AEON OS production secrets (generated $(date -u +%Y-%m-%dT%H:%M:%SZ))
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
AUTH_SECRET=$AUTH_SECRET
AEON_JWT_SECRET=$JWT_SECRET
AEON_API_TOKEN=$API_TOKEN
AEON_MASTER_KMS_KEY=$JWT_SECRET

# Point at your DNS name (A record -> this VM's public IP) for HTTPS.
# Until then Caddy serves plain HTTP on :80.
AEON_DOMAIN=

# First-boot admin seed (ignored if the user already exists).
AEON_ADMIN_EMAIL=
AEON_ADMIN_PASSWORD=
AEON_ADMIN_NAME=Admin

# LLM provider: stub | openai | anthropic | google | mistral | openrouter ...
AEON_LLM_PROVIDER=stub
OPENAI_API_KEY=
ANTHROPIC_API_KEY=
EOF
    chmod 600 .env
fi

# Self-heal .env: creates an admin login and NEXTAUTH_URL if missing
# (covers .env files generated by older bootstrap versions too).
sh "$APP_DIR/scripts/aeon-env-repair.sh" || true

echo ""
echo "Admin login (email + password):"
if [ -f "$APP_DIR/.env" ]; then
    _email=$(sed -n 's/^AEON_ADMIN_EMAIL=//p' "$APP_DIR/.env" | head -1)
    _pass=$(sed -n 's/^AEON_ADMIN_PASSWORD=//p' "$APP_DIR/.env" | head -1)
    echo "  Email:    $_email"
    echo "  Password: $_pass"
fi
echo ""
echo "Set your own password later:"
echo "  sudo sh $APP_DIR/scripts/set-admin.sh you@example.com 'YourPassword123'"

echo ""
echo "NOTE: OCI Security List / NSG must allow ingress TCP 80 and 443."
echo "Starting stack..."
docker compose -f docker-compose.oci.yml up -d --build

# ── Auto-update timer (replaces GitHub Actions deploys) ──────────────────
# Runs every 30 min as root; pulls main and redeploys only when HEAD moved.
if [ "$(id -u)" = 0 ]; then
    sh "$APP_DIR/scripts/install-autoupdate.sh"
else
    echo "Tip: run 'sudo sh scripts/install-autoupdate.sh' to enable the"
    echo "     auto-update timer (pulls main every 30 minutes, no Actions needed)."
fi

echo ""
echo "=== Done. Check status:  docker compose -f docker-compose.oci.yml ps"
echo "Kernel health:           curl http://localhost/health"
echo "Auto-update timer:       systemctl list-timers aeon-autoupdate.timer"
